### PR TITLE
Fixed page containers creation in the right language group

### LINKED ISSUE #10: Page containers created into the wrong language group
New page containers are not created into the selected language group but into the current locale language group.

### PR DESCRIPTION
**Pull request by lucaguindani**
resolves #10

### CODE REVIEW

File: app/controllers/catalog_admin/containers_controller.rb [hunk 1]
```diff
@@ -73,7 +73,7 @@ def container_params
     params.require(:container).permit(
       :slug,
       :row_order_position,
-      :lcoale,
+      :locale,
```
Comment (christiankaiser) [inline app/controllers/catalog_admin/containers_controller.rb]: I don't think this line is still needed. The `locale` param is now called `l` and is retrieved directly from the `params` hash.

Comment (lucaguindani) [reply app/controllers/catalog_admin/containers_controller.rb]: Alright, done !
